### ISSUE TITLE
Bug - Ajout nouvel éditeur impossible

### ISSUE THREAD

**Issue by Sacha-Usan** [UsanRuiz/Bugreport#5]
## **Description du bug**
Lors de l'ajout d'un jeu, lorsque l'on veut créer un nouvel éditeur et qu'on appuis sur _ajouter_, il n'est pas rajouter dans le champ éditeur dans la fenêtre _Ajout jeu video_.

---
## **Marche à suivre**
Depuis la fenêtre _Liste de jeux vidéos_,

1. Cliquer sur le bouton _Ajouter_.
2. Cliquer sur le bouton _Ajouter_ pour ajouter un _Editeur_.
3. Dans le champ _Autre éditeur_, créé un nouvel éditeur.
4. Cliquer sur le bouton _Ajouter_.

#### **résultat observé**
L'éditeur n'est pas rajouté sur le champ _Editeur_ de la fenêtre _Ajout jeu video_.

#### **résultat attendu**
L'éditeur est rajouté sur le champ _Editeur_ de la fenêtre _Ajout jeu video_.

---
## **Environnement**

- PC : SC-C315-PC15
- OS : Windows 10 Education x64
- CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz 3.41GHz
- RAM : 16.0 Go

---
## **Testeur(s)**

- Sacha Usan

**Comment by IlanRuiz** [comment]
Parfait. Le problème sera réglée d'ici peu
